version: '3'

services:
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ./config:/config
    environment:
      - TZ=Asia/Bangkok
    restart: unless-stopped
    privileged: true
    network_mode: host