version: '3'

services:
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ./config:/config
    environment:
      - TZ=Asia/Bangkok
    ports:
      - 8123:8123
    restart: unless-stopped
    privileged: true